CREATE TABLE
    USUARIO (
        ID_USUARIO INT NOT NULL AUTO_INCREMENT,
        NOME VARCHAR(30) NOT NULL,
        EMAIL VARCHAR(30) NOT NULL,
        SENHA VARCHAR(30) NOT NULL,
        PRIMARY KEY (ID_USUARIO)
    );